name: TPManager
version: '1.0'
main: com.yourname.tpmanager.TPManager
api-version: '1.20'
authors: [YourName]
description: A simple teleport request management system.

commands:
  tpa:
    description: Send a teleport request to a player.
    usage: /tpa <player>
  tpaccept:
    description: Accept a teleport request.
    usage: /tpaccept
  tpdeny:
    description: Deny a teleport request.
    usage: /tpdeny